model_list:
  - model_name: Meta-Llama-3.1-405B-Instruct
    litellm_params:
      model: azure_ai/Meta-Llama-3.1-405B-Instruct
      api_key: os.environ/AZURE_AI_API_KEY
      api_base: os.environ/AZURE_AI_API_BASE